on:
  push:
    branches:
      - master
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Change owner to root
        run: chown -R root:root /github/workspace
      - name: checkout
        uses: actions/checkout@v3
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: site
          # Provide personal access token
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
